### ISSUE TITLE
Incorrect Server Version 

### ISSUE THREAD

**Issue by Tamikaschu** [LabyMod/server-media#1128]
```yaml
"gamemodes": {
      "citybuild": {
        "name": "CityBuild", 
        "color": "#E8B50F",
        "versions": "1.20<*"
      }
    },
    ...
``` 
On https://laby.net/server/primeblocks the version is being displayed as 1.7.2-1.20.4 even though `1.20.<*` has been put into the manifest.json. This issue seems to persist for almost every server, e.g.: https://laby.net/server/venade
